version: '3'
services:
  postgres_db:
    image: postgres:latest
    container_name: "cities-db"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cities"
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql